### ISSUE TITLE
Develop Course Page

### ISSUE THREAD

**Issue by kper068** [SOFTENG310-G7/degree-planner#10]
**Is your feature request related to a problem? Please describe.**
As a user, I want to view all the courses available at UoA for my degree so that I can weigh each course against my needs.

**Describe the solution you'd like**
Create the courses page of the website listing all courses in certain degrees at UoA.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

- [x] Courses Page

**Comment by JC4github** [comment]
Finished
