### ISSUE TITLE
Need Search Function for Courses List

### ISSUE THREAD

**Issue by kper068** [SOFTENG310-G7/degree-planner#11]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to quickly find the course i like so that I do not waste my time doing something unproductive.

**Describe the solution you'd like**
Implement a search bar to search through the courses.

**Describe alternatives you've considered**
N/A

**Additional context**

Sub-issues:
- [x] #24

**Comment by JC4github** [comment]
Finished
