### ISSUE TITLE
Create Login and Register Page

### ISSUE THREAD

**Issue by kper068** [SOFTENG310-G7/degree-planner#15]
**Is your feature request related to a problem? Please describe.**
As a returning user, I want to be able to save my degree plans to an account bound under my name so that I can keep track of what plans I have made.

**Describe the solution you'd like**
Implement login and registere forms to enable user account creation and authentication.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

- [x] Register Page
- [x] Login Page

**Comment by JC4github** [comment]
Finished
