### ISSUE TITLE
Make “here” links in README more communicative.

### ISSUE THREAD

**Issue by jaskfla** [SOFTENG310-G7/degree-planner#34]
The README has several links that simply say to “find out about something [here](https://youtu.be/dQw4w9WgXcQ)”.

The presence of the link is great, but doesn’t communicate where it points to. Slightly rewording these can drastically improve the readability of these snippets.

Bad example:

> We’ve updated the Octopus Report, which you can find [here](https://www.youtube.com/watch?v=ebeNeQFUMa0). Feedback is due by Friday.

Good example:

> We’ve updated the [Octopus Report](https://www.youtube.com/watch?v=ebeNeQFUMa0). Feedback is due by Friday.

These examples are taken from Allen Pike’s [Make the Thing a Link](https://allenpike.com/2023/make-the-thing-a-link) article, which is well worth a read. It’s short.

**Comment by JC4github** [comment]
Great idea, please do!
