### ISSUE TITLE
[Feat] Add dependencies for formatting and linting

### ISSUE THREAD

**Issue by hwan513** [SOFTENG310-G7/degree-planner#50]
**Is your feature request related to a problem? Please describe.**
Currently there is no standardised code styling. So during PRs, we would see changed lines of code where the only change is due to the indentation.

**Describe the solution you'd like**
Add Prettier to the project and setup GitHub actions to check for issues on PR.

**Describe alternatives you've considered**
Use Husky as a pre-commit hook to enforce formatting, but that is harder to enforce and some people might have issues with that solution.

**Additional context**
N/A.

**Comment by jaskfla** [comment]
Go ahead
